var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(a){var b=a.toLowerCase(),e=window.document,d=e.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var f=e.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var g=e.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+b+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";f.appendChild(g);d.insertBefore(f,e.head);
a=7==g["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var b=getSize("Width"),e=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),d=CANVAS_WIDTH*e,e=CANVAS_HEIGHT*e,f=0;e<a?(f=a-e,e+=f,d+=CANVAS_WIDTH/CANVAS_HEIGHT*f):d<b&&(f=b-d,d+=f,e+=CANVAS_HEIGHT/CANVAS_WIDTH*f);var f=a/2-e/2,g=b/2-d/2,c=CANVAS_WIDTH/d;if(g*c<-EDGEBOARD_X||f*c<-EDGEBOARD_Y)e=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),b/(CANVAS_WIDTH-2*
EDGEBOARD_X)),d=CANVAS_WIDTH*e,e*=CANVAS_HEIGHT,f=(a-e)/2,g=(b-d)/2,c=CANVAS_WIDTH/d;s_iOffsetX=-1*g*c;s_iOffsetY=-1*f*c;0<=f&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_oStage.canvas.width=d;s_oStage.canvas.height=e;0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",
g+"px");s_iScaleFactor=Math.min(d/CANVAS_WIDTH,e/CANVAS_HEIGHT);s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor}}function createBitmap(a,b,e){var d=new createjs.Bitmap(a),f=new createjs.Shape;b&&e?f.graphics.beginFill("#fff").drawRect(0,0,b,e):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=f;return d}
function createSprite(a,b,e,d,f,g){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-e,-d,f,g);a.hitArea=b;return a}function randomFloatBetween(a,b,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(e))}function shuffle(a){for(var b=a.length,e,d;0!==b;)d=Math.floor(Math.random()*b),--b,e=a[b],a[b]=a[d],a[d]=e;return a}
function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=parseFloat(a-60*b).toFixed(1);var e="",e=10>b?e+("0"+b+":"):e+(b+":");return 10>a?e+("0"+a):e+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var b=a.length,e,d;0<b;)d=Math.floor(Math.random()*b),b--,e=a[b],a[b]=a[d],a[d]=e;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[b]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var b="hidden";b in document?document.addEventListener("visibilitychange",a):(b="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(b="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(b="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),e=0;e<b.length;e++){var d=b[e].split("=");if(d[0]==a)return d[1]}}function playSound(a,b,e){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:e,volume:b}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,b){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=b}
function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(b)}
function CSpriteLibrary(){var a,b,e,d,f,g;this.init=function(c,k,l){e=b=0;d=c;f=k;g=l;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},b++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){f.call(g)};this._onSpriteLoaded=function(){d.call(g);++e===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=960,CANVAS_HEIGHT=540,EDGEBOARD_X=128,EDGEBOARD_Y=42,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,FONT_GAME="Chewy",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_MSG_BOX_LEFT_BUT=6,ON_MSG_BOX_CENTER_BUT=7,ON_MSG_BOX_RIGHT_BUT=8,STATE_GAME_ROLL_IN=0,STATE_GAME_BALL_MOVE=1,STATE_GAME_ROLL_OUT=2,STATE_GAME_SHOOTING=3,STATE_GAME_ATTRACT_BALLS=4,STEP_LENGTH=1.8,BALL_COLORS=5,BALL_ROLLING_IN,
BALL_SHOOTED_SPEED=24,NUM_LEVELS,COMBO_VALUE,EXTRA_SCORE,BALL_DIAMETER,BALL_RADIUS,BALL_DIAMETER_SQUARE,NUM_ROWS_PAGE_LEVEL=3,NUM_COLS_PAGE_LEVEL=5;TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_PLAY="PLAY";TEXT_SCORE="SCORE";TEXT_LEVEL="LEVEL";TEXT_FINAL_SCORE="FINAL SCORE";TEXT_SELECT_LEVEL="SELECT A LEVEL";TEXT_DELETE_SAVINGS="ALL YOUR PROGRESS WILL BE CANCELLED! ARE YOU SURE?";TEXT_NO="NO";TEXT_YES="YES";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";
TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,b,e,d,f,g,c;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();c=new createjs.Container;s_oStage.addChild(c)};this.unload=function(){c.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));c.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(k);d.x=CANVAS_WIDTH/2-k.width/2;d.y=CANVAS_HEIGHT-170;c.addChild(d);a=k.width;b=k.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,b);c.addChild(f);d.mask=
f;e=new createjs.Text("","30px "+FONT_GAME,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT-125;e.shadow=new createjs.Shadow("#000",2,2,2);e.textBaseline="alphabetic";e.textAlign="center";c.addChild(e);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;c.addChild(g)};this.refreshLoader=function(c){e.text=c+"%";f.graphics.clear();c=Math.floor(c*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,c,b)};this._init()}
function CMain(a){var b,e=0,d=0,f=STATE_LOADING,g,c,k;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(35);createjs.Ticker.on("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;this.loadLocalStorage();c=new CPreloader};
this.loadLocalStorage=function(){var a=localStorage.getItem("sorcerer_level");null!==a&&void 0!==a?s_iLastLevel=parseInt(localStorage.getItem("sorcerer_level")):localStorage.setItem("sorcerer_level",1)};this.setLocalStorageLevel=function(a){s_iLastLevel<a&&(s_iLastLevel=a,localStorage.setItem("sorcerer_level",s_iLastLevel))};this.setLocalStorageScore=function(a,c,d){localStorage.setItem("score_level_"+d,a)};this.clearLocalStorage=function(){s_iLastLevel=1;localStorage.clear()};this.getScoreTillLevel=
function(a){for(var c=0,d=0;d<a-1;d++)c+=parseInt(localStorage.getItem("score_level_"+(d+1)));return c};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();b=!0};this.soundLoaded=function(){e++;c.refreshLoader(Math.floor(e/d*100));e===d&&this._allResourcesLoaded()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/combo.ogg","combo"),createjs.Sound.registerSound("./sounds/shot.ogg","shot"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/combo.mp3","combo"),createjs.Sound.registerSound("./sounds/shot.mp3","shot"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack")),d+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_generic_small","./sprites/but_generic_small.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");
s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("hit_area","./sprites/hit_area.png");s_oSpriteLibrary.addSprite("explosion","./sprites/explosion.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("extra_score","./sprites/extra_score.png");s_oSpriteLibrary.addSprite("end_path","./sprites/end_path.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");s_oSpriteLibrary.addSprite("bg_menu_level","./sprites/bg_menu_level.jpg");
s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");for(var a=0;a<BALL_COLORS;a++)s_oSpriteLibrary.addSprite("ball_"+a,"./sprites/ball_"+a+".png");s_oSpriteLibrary.addSprite("bg_game_1","./sprites/bg_game_1.jpg");s_oSpriteLibrary.addSprite("bg_game_2","./sprites/bg_game_2.jpg");s_oSpriteLibrary.addSprite("bg_game_3","./sprites/bg_game_3.jpg");s_oSpriteLibrary.addSprite("bg_game_4","./sprites/bg_game_4.jpg");d+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){e++;c.refreshLoader(Math.floor(e/d*100));e===d&&this._allResourcesLoaded()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._allResourcesLoaded=function(){c.unload();jQuery.getJSON("levels.json",this.onLoadedJSON)};this.onLoadedJSON=function(a){s_oLevelSettings=new CLevelSettings(a);s_oMain.gotoMenu()};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display",
"block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoLevelMenu=function(){new CLevelMenu};this.gotoGame=function(a,c){k=new CGame(g,a,c);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.levelSelected=function(a){a>=s_iLastLevel&&(s_iLastLevel=a);var c=this.getScoreTillLevel(a);this.gotoGame(a,c)};this._update=function(a){if(!1!==b){var c=
(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&k.update();void 0!==s_oStage&&s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundtrack,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oLevelSettings,s_iLastLevel=1;
function CTextButton(a,b,e,d,f,g,c,k){var l,q,m,u,r,n,t,v,z,D;this._init=function(a,c,d,f,b,e,k){l=!1;u=[];r=[];z=createBitmap(d);q=d.width;m=d.height;var g=Math.ceil(k/20);t=new createjs.Text(f,""+k+"px "+b,"#000000");t.textAlign="center";var C=t.getBounds();t.x=d.width/2+g;t.y=(d.height-C.height)/2+g;v=new createjs.Text(f,k+"px "+b,e);v.textAlign="center";C=v.getBounds();v.x=d.width/2;v.y=(d.height-C.height)/2;n=new createjs.Container;n.x=a;n.y=c;n.regX=d.width/2;n.regY=d.height/2;n.addChild(z,
t,v);D.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");D.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){l=!1;z.filters=[];z.cache(0,0,q,m)};this.disable=function(){l=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);z.filters=[new createjs.ColorMatrixFilter(a)];z.cache(0,0,q,m)};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};
this.addEventListener=function(a,c,d){u[a]=c;r[a]=d};this.buttonRelease=function(){l||(playSound("press_but",1,0),n.scaleX=1,n.scaleY=1,u[ON_MOUSE_UP]&&u[ON_MOUSE_UP].call(r[ON_MOUSE_UP]))};this.buttonDown=function(){l||(n.scaleX=.9,n.scaleY=.9,u[ON_MOUSE_DOWN]&&u[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN]))};this.setPosition=function(a,c){n.x=a;n.y=c};this.changeText=function(a){v.text=a;t.text=a};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=
function(){return n.x};this.getY=function(){return n.y};D=k;this._init(a,b,e,d,f,g,c);return this}
function CGfxButton(a,b,e){var d,f,g=[],c;this._init=function(a,b,e){d=[];f=[];c=createBitmap(e);c.x=a;c.y=b;c.regX=e.width/2;c.regY=e.height/2;s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){d[a]=c;f[a]=b};this.addEventListenerWithParams=
function(a,c,b,e){d[a]=c;f[a]=b;g=e};this.buttonRelease=function(){playSound("press_but",1,0);c.scaleX=1;c.scaleY=1;d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(f[ON_MOUSE_UP],g)};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],g)};this.setPosition=function(a,d){c.x=a;c.y=d};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(a,
b,e);return this}
function CToggle(a,b,e,d){var f,g,c,k;this._init=function(a,d,b,e){g=[];c=[];var r=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});f=e;k=createSprite(r,"state_"+f,b.width/2/2,b.height/2,b.width/2,b.height);k.x=a;k.y=d;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this._initListener=
function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,d,b){g[a]=d;c[a]=b};this.setActive=function(a){f=a;k.gotoAndStop("state_"+f)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("press_but",1,0);f=!f;k.gotoAndStop("state_"+f);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(c[ON_MOUSE_UP],f)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN])};this.setPosition=function(a,c){k.x=
a;k.y=c};this._init(a,b,e,d)}
function CMenu(){var a,b,e,d,f=null,g,c;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);1===s_iLastLevel?(d=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_play"),!0),d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this)):(d=new CGfxButton(CANVAS_WIDTH/2-150,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_play"),!0),d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this),f=new CGfxButton(CANVAS_WIDTH/2+150,
CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_continue"),!0),f.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this));if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var k=s_oSpriteLibrary.getSprite("audio_icon");a=CANVAS_WIDTH-k.height/2;b=k.height/2;g=new CToggle(a,b,k,s_bAudioActive);g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);s_oSoundtrack=playSound("soundtrack",1,-1)}c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(c);
createjs.Tween.get(c).to({alpha:0},400).call(function(){c.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){d.unload();d=null;null!==f&&f.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;s_oStage.removeChild(e);e=null;s_oStage.removeChild(c);s_oMenu=c=null};this.refreshButtonPos=function(c,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(a-c,d+b)};this._exitFromMenu=function(){this.unload();s_oMain.gotoLevelMenu();$(s_oMain).trigger("start_session")};
this._onButPlayRelease=function(){if(1<s_iLastLevel){var a=new CMsgBox(TEXT_DELETE_SAVINGS,TEXT_NO,"",TEXT_YES);a.addEventListener(ON_MSG_BOX_LEFT_BUT,function(){a.hide()},this);a.addEventListener(ON_MSG_BOX_RIGHT_BUT,function(){a.hide();s_oMain.clearLocalStorage();s_oMenu._exitFromMenu()},this)}else s_oMenu._exitFromMenu()};this._onButContinueRelease=function(){s_oMenu._exitFromMenu()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oMenu=this;
this._init()}var s_oMenu=null;
function CGame(a,b,e){var d=!1,f,g,c,k,l,q,m,u,r=-1,n,t,v,z,D,E,y,h,p,x,w,B=null,K=null,C=null,A,H,F,I,G,L,J;this._init=function(a,c){y=a;k=c;s_oBezier=new CBezier;J=new createjs.Container;H=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getBgForLevel(y)));J.addChild(H);s_oStage.addChild(J);H.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);A=new CHero;G=new createjs.Container;I=new createjs.Container;L=new createjs.Container;s_oStage.addChild(G);s_oStage.addChild(I);s_oStage.addChild(L);F=new CInterface(k);
this.reset();if(!1===s_bMobile){var b=this;s_oStage.addEventListener("stagemousemove",function(a){b._onMouseMove(a.stageX,a.stageY)})}d=!0};this.unload=function(){d=!1;clearInterval(v);createjs.Sound.stop();F.unload();A.unload();s_oStage.removeAllChildren()};this.reset=function(){f=!0;c=g=!1;u=s_oLevelSettings.getBallSpeedForLevel(y);m=s_oLevelSettings.getBallNumberForLevel(y);D=s_oLevelSettings.getBallColorsForLevel(y);BALL_ROLLING_IN=Math.floor(.33*m);n=0;q=t=1;l=E=0;A.reset(s_oLevelSettings.getHeroPosForLevel(y),
D);null!==K&&(G.removeChild(K),G.removeChild(C));this._initCurve();this._initBall();F.refreshLevel(y);$(s_oMain).trigger("start_level",y)};this._normalize=function(a){var c=this._length(a);return 0<c?{x:a.x/c,y:a.y/c}:a};this._length=function(a){return Math.sqrt(a.x*a.x+a.y*a.y)};this._dotProductV2=function(a,c){return a.x*c.x+a.y*c.y};this._angleBetweenVectors=function(a,c){var d=Math.acos(this._dotProductV2(a,c)/(this._length(a)*this._length(c)));return!0===isNaN(d)?0:d};this._rot90CW=function(a){return{x:a.y,
y:-a.x}};this._rot90CCW=function(a){return{x:-a.y,y:a.x}};this._rotateVector2D=function(a,c){return{x:c.x*Math.cos(a)+c.y*Math.sin(a),y:c.x*-Math.sin(a)+c.y*Math.cos(a)}};this._initCurve=function(){var a,c;a=s_oLevelSettings.getCurveForLevel(y);var d=new createjs.Graphics;p=[];for(c=0;c<a.length-2;++c)for(var b=0===c?new createjs.Point(a[0][0],a[0][1]):new createjs.Point((a[c][0]+a[c+1][0])/2,(a[c][1]+a[c+1][1])/2),e=new createjs.Point(a[c+1][0],a[c+1][1]),f=c<=a.length-4?new createjs.Point((a[c+
1][0]+a[c+2][0])/2,(a[c+1][1]+a[c+2][1])/2):new createjs.Point(a[c+2][0],a[c+2][1]),b=s_oBezier.init(b,e,f,STEP_LENGTH),e=1;e<=b;++e)f=s_oBezier.getAnchorPoint(e),p.push(f);d.setStrokeStyle(4);d.beginStroke("#00a29b");d.beginFill("#221910");b={x:p[1][0]-p[0][0],y:p[1][1]-p[0][1]};b=this._normalize(b);b=this._rot90CW(b);b.x*=15;b.y*=15;b.x+=p[0][0];b.y+=p[0][1];a=b.x;c=b.y;d.moveTo(b.x,b.y);for(e=1;e<p.length-1;e++)b={x:p[e+1][0]-p[e][0],y:p[e+1][1]-p[e][1]},b=this._normalize(b),b=this._rot90CW(b),
b.x*=15,b.y*=15,b.x+=p[e][0],b.y+=p[e][1],d.lineTo(b.x,b.y);d.lineTo(b.x,b.y);b={x:p[p.length-1][0]-p[p.length-2][0],y:p[p.length-1][1]-p[p.length-2][1]};b=this._normalize(b);b=this._rot90CCW(b);b.x*=15;b.y*=15;b.x+=p[p.length-1][0];b.y+=p[p.length-1][1];d.lineTo(b.x,b.y);for(e=p.length-2;1<e;e--)b={x:p[e][0]-p[e-1][0],y:p[e][1]-p[e-1][1]},b=this._normalize(b),b=this._rot90CCW(b),b.x*=15,b.y*=15,b.x+=p[e][0],b.y+=p[e][1],d.lineTo(b.x,b.y);d.lineTo(a,c);d.endFill();K=new createjs.Shape(d);G.addChild(K);
d=p.length;a=s_oSpriteLibrary.getSprite("end_path");C=createBitmap(a);C.x=p[d-9][0];C.y=p[d-9][1];C.regX=a.width/2;C.regY=a.height/2;G.addChild(C);G.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT)};this._initBall=function(){h=[];var a=this.getRandomBall();h.unshift(a);a.setPos(16,p);r=STATE_GAME_ROLL_IN};this.getRandomBall=function(){m--;return new CBall(Math.floor(Math.random()*D),I)};this._pushNextBall=function(a,b){var d=[];d.push(h[a]);for(var e=a;e<h.length-1;++e)if(16>=h[e+1].getFotogram()-h[e].getFotogram())16>
h[e+1].getFotogram()-h[e].getFotogram()&&h[e+1].setPos(h[e].getFotogram()+16,p),d.push(h[e+1]);else break;for(e=0;e<d.length;++e)d[e].increasePos(b,p);if(h[h.length-1].getFotogram()>=p.length-17){f=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.pause(),playSound("game_over",1,0).addEventListener("complete",this._onSoundGameOverComplete);s_oStage.removeEventListener("stagemousemove");c=g=!1;q=1;h[h.length-1].unload();h.splice(h.length-1,1);r=STATE_GAME_ROLL_OUT}};this.onIntroduceBall=
function(){if(0!==h.length&&(s_oGame._pushNextBall(0,1),32===h[0].getFotogram()&&0!==m)){var a=s_oGame.getRandomBall();h.unshift(a);a.setPos(16,p)}};this.shoot=function(){playSound("shot",1,0);var a=(A.getRotation()+90)*Math.PI/180,b=A.getCurrentBall();b.changePos(A.getX()+60*Math.cos(a),A.getY()+60*Math.sin(a));I.addChild(b.getSprite());b.setContainer(I);x.push([b,a]);r=STATE_GAME_SHOOTING};this._checkCollision=function(a){a=a[0];for(var b=0;b<h.length;++b)if((h[b].getX()-a.getX())*(h[b].getX()-
a.getX())+(h[b].getY()-a.getY())*(h[b].getY()-a.getY())<=BALL_DIAMETER_SQUARE)return b;return-1};this._insertBall=function(a,b,c){var d;"next"===c?(d=h[b].getFotogram()+16,h[b+1]&&32>h[b+1].getFotogram()-h[b].getFotogram()&&(w.push([a,h[b+1]]),g=!0)):h[b-1]&&32>h[b].getFotogram()-h[b-1].getFotogram()?(d=h[b-1].getFotogram()+16,w.push([a,h[b]]),g=!0):d=h[b].getFotogram()-16;b=p[d][0];c=p[d][1];var e=this;createjs.Tween.get(a.getSprite()).to({x:b,y:c},200).call(function(){e.motionFinished(a,d)})};this.motionFinished=
function(a,b){for(var c,d=0;d<h.length;++d){if(h[d].getFotogram()>b){c=d;break}d===h.length-1&&(c=d+1)}w.splice(w.indexOf(a),1);a.setPos(b,p);h.splice(c,0,a);h[c-1]&&h[c-1].getIndex()===h[c].getIndex()&&17<h[c].getFotogram()-h[c-1].getFotogram()&&this._addToBallAttracted(h[c]);h[c+1]&&h[c+1].getIndex()===h[c].getIndex()&&17<h[c+1].getFotogram()-h[c].getFotogram()&&this._addToBallAttracted(h[c+1]);this._clearCheck(c,!0)};this._addToBallAttracted=function(a){null===B&&(B=[]);B.push(a);setTimeout(function(){c=
!0},400)};this._clearCheck=function(a,b){var c=[];c.push(h[a]);for(var d=h[a].getIndex(),e=a+1;h[e];)if(h[e].getIndex()===d)if(17>=h[e].getFotogram()-h[e-1].getFotogram())c.push(h[e]),++e;else if(b)break;else c.push(h[e]),++e;else break;for(e=a-1;h[e];)if(h[e].getIndex()===d)if(17>=h[e+1].getFotogram()-h[e].getFotogram())c.push(h[e]),--e;else if(b)break;else c.push(h[e]),--e;else break;++e;2<c.length&&b&&this._clearBall(e,c);return c.length};this._attract=function(){if(0!==B.length)for(var a=0;a<
B.length;++a){var b=h.indexOf(B[a]);if(-1!==b&&h[b-1])if(B[a].getIndex()===h[b-1].getIndex()){var d=19<B[a].getFotogram()-h[b-1].getFotogram()?3:B[a].getFotogram()-h[b-1].getFotogram()-16;this._pushNextBall(b,-d);16>=B[a].getFotogram()-h[b-1].getFotogram()&&(q++,B.splice(a,1),this._clearCheck(b-1,!0),0===B.length&&(c=!1,q=1))}else B.splice(a,1),n>t&&(t=n),n=0}else c=!1,q=1};this._checkPushCollision=function(){if(0!==w.length)for(var a=0;a<w.length;++a){for(var b=(w[a][0].getX()-w[a][1].getX())*(w[a][0].getX()-
w[a][1].getX())+(w[a][0].getY()-w[a][1].getY())*(w[a][0].getY()-w[a][1].getY()),b=b<BALL_DIAMETER_SQUARE?!0:!1,c=0;b;)++c,b=(w[a][0].getX()-p[w[a][1].getFotogram()+c][0])*(w[a][0].getX()-p[w[a][1].getFotogram()+c][0])+(w[a][0].getY()-p[w[a][1].getFotogram()+c][1])*(w[a][0].getY()-p[w[a][1].getFotogram()+c][1]),b=b<BALL_DIAMETER_SQUARE?!0:!1;b=h.indexOf(w[a][1]);-1!==b&&this._pushNextBall(b,c)}else g=!1};this._clearBall=function(a,b){++n;playSound("combo",1,0);for(var c=0,d=0;d<b.length;++d)b[d].explode(),
c+=COMBO_VALUE;c*=q;k+=c;l+=c;F.refreshScore(k);h.length===b.length&&(f=!1,z=h[h.length-1].getFotogram(),setTimeout(this._gamePass,600),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(s_oSoundtrack.pause(),playSound("win",1,0).addEventListener("complete",this._onSoundGameOverComplete));h.splice(a,b.length);0===m&&this._checkColor(b[0].getIndex());h[a-1]&&h[a]&&h[a-1].getIndex()===h[a].getIndex()?(3>this._clearCheck(a,!1)&&(n>t&&(t=n),n=0),this._addToBallAttracted(h[a])):(n>t&&(t=n),n=0)};this._gamePass=
function(){v=setInterval(s_oGame._extraScore,u)};this._extraScore=function(){z+16<p.length-17?(z+=16,new CExtraScore(p[z][0],p[z][1],L),k+=EXTRA_SCORE,l+=EXTRA_SCORE,F.refreshScore(k)):($(s_oMain).trigger("end_level",y),clearInterval(v),s_oStage.removeEventListener("stagemousemove"),f=!1,s_oMain.setLocalStorageScore(l,k,y),y++,y>s_oLevelSettings.getNumLevels()?(y--,F.win(k)):(s_oMain.setLocalStorageLevel(y),F.nextLevel(y,k)))};this._checkColor=function(a){for(var b=0;b<h.length;++b)if(h[b].getIndex()===
a)return;for(b=0;b<x.length;++b)if(x[b].getIndex()===a)return;A.colorCleared(a)};this.nextLevel=function(){J.removeChild(H);H=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getBgForLevel(y)));J.addChild(H);this.reset();d=!0};this.onShot=function(a,b){if(f&&A.canShoot()){if(s_bMobile){var c=a-A.getX()*s_iScaleFactor,d=b-A.getY()*s_iScaleFactor;A.rotate(180*Math.atan2(d,c)/Math.PI-90)}this.shoot()}};this._onMouseMove=function(a,b){var c=a-A.getX()*s_iScaleFactor,d=b-A.getY()*s_iScaleFactor;
A.rotate(180*Math.atan2(d,c)/Math.PI-90)};this.onExit=function(){createjs.Sound.stop();this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",k)};this._onSoundGameOverComplete=function(){s_oSoundtrack.resume()};this._updateMove=function(){E+=s_iTimeElaps;E>u&&(E=0,this.onIntroduceBall())};this._updateRollOut=function(){for(var a=h.length-1;0<=a;--a)h[a].getFotogram()>p.length-17?(h[a].unload(),h.splice(a,1),0===h.length&&(r=-1,F.gameOver(k))):h[a].increasePos(8,
p)};this._updateRollIn=function(){if(h.length<BALL_ROLLING_IN){for(var a=0;a<h.length;++a)h[a].increasePos(4,p);32===h[0].getFotogram()&&(a=this.getRandomBall(),h.unshift(a),a.setPos(16,p))}else r=-1,x=[],w=[],A.start(),r=STATE_GAME_BALL_MOVE};this._updateShooting=function(){if(0!==x.length)for(var a=0;a<x.length;++a)if(0<x[a][0].getX()&&x[a][0].getX()<CANVAS_WIDTH&&0<x[a][0].getY()&&x[a][0].getY()<CANVAS_HEIGHT){var b=this._checkCollision(x[a]);if(-1===b)x[a][0].increasePosWithNumbers(Math.cos(x[a][1])*
BALL_SHOOTED_SPEED,Math.sin(x[a][1])*BALL_SHOOTED_SPEED);else{var c=x[a][0],d=x[a][1],e=Math.sqrt((h[b].getX()-c.getX())*(h[b].getX()-c.getX())+(h[b].getY()-c.getY())*(h[b].getY()-c.getY()));x[a][0].decreasePos((BALL_DIAMETER-e)*Math.cos(d),(BALL_DIAMETER-e)*Math.sin(d));var d=p[h[b].getFotogram()-BALL_RADIUS][0],e=p[h[b].getFotogram()-BALL_RADIUS][1],d=Math.sqrt((c.getX()-d)*(c.getX()-d)+(c.getY()-e)*(c.getY()-e)),e=p[h[b].getFotogram()+BALL_RADIUS][0],f=p[h[b].getFotogram()+BALL_RADIUS][1],c=Math.sqrt((c.getX()-
e)*(c.getX()-e)+(c.getY()-f)*(c.getY()-f));this._insertBall(x[a][0],b,d>c?"next":"previous");x.splice(a,1)}}else x[a][0].unload(),x.splice(a,1);else r=-1};this.update=function(){if(!1!==d)switch(!0===c&&this._attract(),!0===g&&this._checkPushCollision(),r){case STATE_GAME_ROLL_IN:this._updateRollIn();break;case STATE_GAME_ROLL_OUT:this._updateRollOut();break;case STATE_GAME_SHOOTING:this._updateShooting();this._updateMove();break;default:this._updateMove()}};s_oGame=this;COMBO_VALUE=a.combo_value;
EXTRA_SCORE=a.extra_score;this._init(b,e)}var s_oGame,s_oBezier;
function CInterface(a){var b,e,d,f,g,c,k,l,q,m,u,r,n,t,v;this._init=function(a){f=d=10;m=new createjs.Text(TEXT_SCORE+" "+a,"38px "+FONT_GAME,"#fff");m.x=d;m.y=f;m.textAlign="left";s_oStage.addChild(m);b=10;e=50;q=new createjs.Text(TEXT_LEVEL+" "+s_iLastLevel,"30px "+FONT_GAME,"#fff");q.x=b;q.y=e;q.textAlign="left";s_oStage.addChild(q);var D=this;r=createBitmap(s_oSpriteLibrary.getSprite("hit_area"));s_oStage.addChild(r);r.on("pressup",function(a){D._onTapScreen(a.stageX,a.stageY)});a=s_oSpriteLibrary.getSprite("but_exit");
g=CANVAS_WIDTH-a.width/2;c=a.height/2;u=new CGfxButton(g,c,a,!0);u.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=u.getX()-a.width,l=a.height/2,n=new CToggle(k,l,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);v=new CNextLevel;t=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){u.unload();u=null;!1===DISABLE_SOUND_MOBILE&&
(n.unload(),n=null);s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(a,r){m.x=d+a;m.y=f+r;q.x=b+a;q.y=e+r;u.setPosition(g-a,c+r);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||n.setPosition(k-a,r+l)};this._onTapScreen=function(a,b){s_oGame.onShot(a,b)};this.gameOver=function(a){t.show(a,!1)};this.win=function(a){t.show(a,!0)};this.nextLevel=function(a,b){v.show(a,b)};this.refreshScore=function(a){m.text=TEXT_SCORE+" "+a};this.refreshLevel=function(a){q.text=TEXT_LEVEL+" "+
a};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CEndPanel(a){var b,e,d,f,g,c;this._init=function(a){b=createBitmap(a);g=new createjs.Text(TEXT_CONGRATS,"28px "+FONT_GAME,"#000");g.x=CANVAS_WIDTH/2+22;g.y=CANVAS_HEIGHT/2-68;g.textAlign="center";f=new createjs.Text(TEXT_CONGRATS,"28px "+FONT_GAME,"#ffffff");f.x=CANVAS_WIDTH/2+20;f.y=CANVAS_HEIGHT/2-70;f.textAlign="center";e=new createjs.Text(TEXT_FINAL_SCORE+"\n99999","32px "+FONT_GAME,"#000");e.x=CANVAS_WIDTH/2+21;e.y=CANVAS_HEIGHT/2+11;e.textAlign="center";d=new createjs.Text(TEXT_FINAL_SCORE+
"\n99999","32px "+FONT_GAME,"#ffffff");d.x=CANVAS_WIDTH/2+20;d.y=CANVAS_HEIGHT/2+10;d.textAlign="center";c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(b,e,d,g,f);s_oStage.addChild(c)};this.unload=function(){c.off("mousedown",this._onExit);s_oStage.removeChild(c)};this._initListener=function(){c.on("mousedown",this._onExit);$(s_oMain).trigger("show_interlevel_ad")};this.show=function(a,b){b?(g.text=TEXT_CONGRATS,f.text=TEXT_CONGRATS):(g.text=TEXT_GAMEOVER,f.text=TEXT_GAMEOVER);e.text=
TEXT_FINAL_SCORE+"\n "+a;d.text=TEXT_FINAL_SCORE+"\n "+a;c.visible=!0;var q=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){q._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){c.off("mousedown");s_oGame.onExit()};this._init(a);return this}
function CTweenController(){this.tweenValue=function(a,b,e){return a+e*(b-a)};this.easeLinear=function(a,b,e,d){return e*a/d+b};this.easeInCubic=function(a,b,e,d){d=(a/=d)*a*a;return b+e*d};this.easeBackInQuart=function(a,b,e,d){d=(a/=d)*a;return b+e*(2*d*d+2*d*a+-3*d)};this.easeInBack=function(a,b,e,d){return e*(a/=d)*a*(2.70158*a-1.70158)+b};this.easeOutCubic=function(a,b,e,d){return e*((a=a/d-1)*a*a+1)+b}}
function CLevelSettings(a){var b,e,d,f,g,c,k;this._init=function(a){b=a;NUM_LEVELS=Object.keys(b).length;this._initBallSpeed();this._initBallNumber();this._initBallColors();this._initHeroPos();this._initCurveLevel();this._initBgLevel()};this._initBallSpeed=function(){e=[];for(var a=0;a<NUM_LEVELS;a++)e[a]=b[a].ball_speed};this._initBallNumber=function(){d=[];for(var a=0;a<NUM_LEVELS;a++)d[a]=b[a].ball_number};this._initBallColors=function(){f=[];for(var a=0;a<NUM_LEVELS;a++)f[a]=b[a].num_colors};
this._initHeroPos=function(){g=[];for(var a=0;a<NUM_LEVELS;a++)g[a]=new createjs.Point(b[a].hero_pos.x,b[a].hero_pos.y)};this._initCurveLevel=function(){c=[];for(var a=0;a<NUM_LEVELS;a++){c[a]=[];for(var d=b[a].curve_point,e=0;e<d.length;e++)c[a].push([d[e].x,d[e].y])}};this._initBgLevel=function(){k=[];for(var a=0;a<NUM_LEVELS;a++)k[a]=b[a].bg_image};this.getBallSpeedForLevel=function(a){return e[a-1]};this.getBallNumberForLevel=function(a){return d[a-1]};this.getBallColorsForLevel=function(a){return f[a-
1]};this.getHeroPosForLevel=function(a){return g[a-1]};this.getCurveForLevel=function(a){return c[a-1]};this.getNumLevels=function(){return c.length};this.getBgForLevel=function(a){return k[a-1]};this._init(a)}
function CHero(){var a=!1,b,e,d,f,g,c,k,l,q,m;this._init=function(){var a=s_oSpriteLibrary.getSprite("hero");m=new createjs.Container;m.regX=a.width/2;m.regY=a.height/2;s_oStage.addChild(m);k=createBitmap(a);k.x=0;k.y=0;m.addChild(k);l=new createjs.Shape;l.graphics.beginFill("rgba(255,0,0,0.01)").drawCircle(40,110,16);m.addChild(l);q=new createjs.Shape;q.graphics.beginFill("rgba(255,0,0,0.01)").drawCircle(120,60,6);m.addChild(q);b=a.width;e=a.height};this.reset=function(a,b){d=b;void 0!==g&&null!==
g&&g.unload();void 0!==c&&null!==c&&c.unload();m.x=a.x;m.y=a.y;f=[];for(var e=0;e<d;e++)f[e]=!0};this.unload=function(){};this.rotate=function(a){m.rotation=a};this.start=function(){g=this._getRandomBall();g.changePos(b/2-25,e/2+20);g.getSprite().mask=l;c=this._getRandomBall();c.changePos(120,e/2-12);c.getSprite().mask=q;var a=this;createjs.Tween.get(g.getSprite()).to({y:g.getY()+25},300).call(function(){a._onBallReady()});createjs.Tween.get(c.getSprite()).to({y:c.getY()+16},300)};this._getRandomBall=
function(){var a;if(!0===this._checkIfAllColorsNotAvailable())return null;do{var b=Math.floor(Math.random()*d),c=!1;if(!0===f[b]){a=new CBall(b,m);break}}while(!1===c);return a};this._checkIfAllColorsNotAvailable=function(){for(var a=!0,b=0;b<f.length;b++)!0===f[b]&&(a=!1);return a};this._nextShoot=function(){null!==g&&g.unload();g=c;g.changePos(b/2-25,e/2+20);g.getSprite().mask=l;c=this._getRandomBall();c.changePos(120,e/2-12);c.getSprite().mask=q;var a=this;createjs.Tween.get(g.getSprite()).to({y:g.getY()+
25},300).call(function(){a._onBallReady()});createjs.Tween.get(c.getSprite()).to({y:c.getY()+16},300)};this.colorCleared=function(a){f[a]=!1;g.getIndex()===a&&(g.unload(),g=this._getRandomBall(),null!==g&&(g.changePos(b/2-25,e/2+45),g.getSprite().mask=l));c.getIndex()===a&&(c.unload(),c=this._getRandomBall(),null!==c&&(c.changePos(120,e/2+4),c.getSprite().mask=q))};this._onBallReady=function(){a=!0};this.getCurrentBall=function(){a=!1;var b=g;this._nextShoot();return b};this.getX=function(){return m.x};
this.getY=function(){return m.y};this.getRotation=function(){return m.rotation};this.canShoot=function(){return a};this._init()}
function CBezier(){var a,b,e,d,f,g,c,k,l,q,m,u;this.init=function(r,n,t,v){a=r;b=n;e=t;f=a.x-2*b.x+e.x;g=a.y-2*b.y+e.y;c=2*b.x-2*a.x;k=2*b.y-2*a.y;l=4*(f*f+g*g);q=4*(f*c+g*k);m=c*c+k*k;u=this._length(1);d=Math.floor(u/v);u%v>v/2&&d++;return d};this._speed=function(a){return Math.sqrt(l*a*a+q*a+m)};this._length=function(a){var b=Math.sqrt(m+a*(q+l*a));return(2*Math.sqrt(l)*(2*l*a*b+q*(b-Math.sqrt(m)))+(q*q-4*l*m)*(Math.log(q+2*Math.sqrt(l)*Math.sqrt(m))-Math.log(q+2*l*a+2*Math.sqrt(l)*b)))/(8*Math.pow(l,
1.5))};this.invertL=function(a,b){var c=a,d;do{d=c-(this._length(c)-b)/this._speed(c);if(1E-6>Math.abs(c-d))break;c=d}while(1);return d};this.getAnchorPoint=function(c){if(0<=c&&c<=d){var f=c/d,f=this.invertL(f,f*u);c=(1-f)*(1-f)*a.x+2*(1-f)*f*b.x+f*f*e.x;var g=(1-f)*(1-f)*a.y+2*(1-f)*f*b.y+f*f*e.y,k=new createjs.Point((1-f)*a.x+f*b.x,(1-f)*a.y+f*b.y),f=new createjs.Point((1-f)*b.x+f*e.x,(1-f)*b.y+f*e.y);return[c,g,180*Math.atan2(f.y-k.y,f.x-k.x)/Math.PI]}return[]}}
function CBall(a,b){var e,d,f,g,c;this._init=function(a,b){e=a;d=0;c=b;var g=s_oSpriteLibrary.getSprite("ball_"+e);BALL_DIAMETER=g.width;BALL_DIAMETER_SQUARE=BALL_DIAMETER*BALL_DIAMETER;BALL_RADIUS=BALL_DIAMETER/2;g=new createjs.SpriteSheet({images:[g],frames:{width:BALL_DIAMETER,height:BALL_DIAMETER,regX:BALL_RADIUS,regY:BALL_RADIUS},animations:{move:[0,49]}});f=createSprite(g,null,BALL_RADIUS,BALL_RADIUS,BALL_DIAMETER,BALL_DIAMETER);f.stop();c.addChild(f)};this.unload=function(){c.removeChild(g);
c.removeChild(f)};this.nextFrame=function(){f.gotoAndStop(50===f.currentFrame+1?0:f.currentFrame+1)};this.prevFrame=function(){f.gotoAndStop(0>f.currentFrame-1?49:f.currentFrame-1)};this.setPos=function(a,b){a>d?this.nextFrame():a<d&&this.prevFrame();d=a;f.x=b[d][0];f.y=b[d][1];f.rotation=b[d][2]-90};this.changePos=function(a,b){f.x=a;f.y=b};this.increasePosWithNumbers=function(a,b){f.x+=a;f.y+=b};this.decreasePos=function(a,b){f.x-=a;f.y-=b};this.increasePos=function(a,b){this.setPos(d+a,b)};this.setContainer=
function(a){f.mask=null;c=a};this.explode=function(){var a={images:[s_oSpriteLibrary.getSprite("explosion")],frames:{width:30,height:30,regX:15,regY:15},animations:{show:[0,19],hide:[20]}},b=this,a=new createjs.SpriteSheet(a,"show");g=new createjs.Sprite(a);g.addEventListener("animationend",function(){b.onExplosionEnd()});c.addChild(g);g.x=f.x;g.y=f.y;g.gotoAndPlay("show");f.visible=!1};this.onExplosionEnd=function(){c.removeChild(g);c.removeChild(f)};this.rollInStage=function(){};this.getFotogram=
function(){return d};this.getSprite=function(){return f};this.getIndex=function(){return e};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,b)}
function CNextLevel(){var a,b,e,d,f,g;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));e=new createjs.Text("LEVEL 2","48px "+FONT_GAME,"#000");e.x=CANVAS_WIDTH/2+32;e.y=CANVAS_HEIGHT/2-70;e.textAlign="center";b=new createjs.Text("LEVEL 2","48px "+FONT_GAME,"#ffffff");b.x=CANVAS_WIDTH/2+30;b.y=CANVAS_HEIGHT/2-72;b.textAlign="center";f=new createjs.Text("SCORE 99999","34px "+FONT_GAME,"#000");f.x=CANVAS_WIDTH/2+32;f.y=CANVAS_HEIGHT/2+12;f.textAlign="center";d=new createjs.Text("SCORE 99999",
"34px "+FONT_GAME,"#ffffff");d.x=CANVAS_WIDTH/2+30;d.y=CANVAS_HEIGHT/2+10;d.textAlign="center";g=new createjs.Container;g.alpha=0;g.visible=!1;g.addChild(a,e,b,f,d);s_oStage.addChild(g)};this.show=function(a,k){e.text=TEXT_LEVEL+" "+a;b.text=TEXT_LEVEL+" "+a;f.text=TEXT_SCORE+" "+k;d.text=TEXT_SCORE+" "+k;g.visible=!0;var l=this;createjs.Tween.get(g).to({alpha:1},500).call(function(){l._initListener()})};this._initListener=function(){g.on("mousedown",this._onExit);$(s_oMain).trigger("show_interlevel_ad")};
this._onExit=function(){g.off("mousedown");g.alpha=0;g.visible=!1;s_oGame.nextLevel()};this._init()}function CExtraScore(a,b,e){var d;this._init=function(a,b,c){var e=s_oSpriteLibrary.getSprite("extra_score");d=createBitmap(e);d.x=a;d.y=b;d.regX=e.width/2;d.regY=e.height/2;d.alpha=0;c.addChild(d);createjs.Tween.get(d).to({alpha:1},1E3).call(function(){c.removeChild(d)})};this._init(a,b,e)}
function CLevelMenu(){var a,b,e,d,f,g,c,k,l,q,m,u,r,n=null,t=null,v,z;this._init=function(){c=0;z=new createjs.Container;s_oStage.addChild(z);var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu_level"));z.addChild(l);f=CANVAS_WIDTH/2;g=18;v=new createjs.Text(TEXT_SELECT_LEVEL,"50px "+FONT_GAME,"#fff");v.x=f;v.y=g;v.textAlign="center";s_oStage.addChild(v);l=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-l.width/2;d=l.height/2;u=new CGfxButton(e,d,l,!0);u.addEventListener(ON_MOUSE_UP,this._onExit,
this);k=l.height;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=u.getX()-l.width,b=l.height/2,r=new CToggle(a,b,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this._checkBoundLimits();q=[];for(var l=Math.floor((CANVAS_WIDTH-2*EDGEBOARD_X)/NUM_COLS_PAGE_LEVEL)/2,E=0,y=0;y<NUM_COLS_PAGE_LEVEL;y++)q.push(E),E+=2*l;m=[];this._createNewLevelPage(0,NUM_LEVELS);if(1<m.length){for(l=1;l<m.length;l++)m[l].visible=!1;n=new CGfxButton(CANVAS_WIDTH/
2+280,CANVAS_HEIGHT-80,s_oSpriteLibrary.getSprite("arrow_right"),!0);n.addEventListener(ON_MOUSE_UP,this._onRight,this);t=new CGfxButton(CANVAS_WIDTH/2-280,CANVAS_HEIGHT-80,s_oSpriteLibrary.getSprite("arrow_left"),!0);t.addEventListener(ON_MOUSE_UP,this._onLeft,this)}this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<l.length;a++)l[a].unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.unload();u.unload();null!==t&&(t.unload(),n.unload());s_oLevelMenu=null};this.refreshButtonPos=
function(c,f){v.y=g+f;u.setPosition(e-c,d+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(a-c,f+b)};this._checkBoundLimits=function(){for(var a=s_oSpriteLibrary.getSprite("but_level"),b=0,c=CANVAS_HEIGHT-2*EDGEBOARD_Y-2*k,d=0;b<c;)b+=a.height+20,d++;NUM_ROWS_PAGE_LEVEL>d&&(NUM_ROWS_PAGE_LEVEL=d);c=b=0;d=CANVAS_WIDTH-2*EDGEBOARD_X;for(a=s_oSpriteLibrary.getSprite("but_level");c<d;)c+=a.width/2+5,b++;NUM_COLS_PAGE_LEVEL>b&&(NUM_COLS_PAGE_LEVEL=b)};this._createNewLevelPage=function(a,b){var c=
new createjs.Container;z.addChild(c);m.push(c);l=[];for(var d=0,e=0,f=1,g=!1,k=s_oSpriteLibrary.getSprite("but_level"),n=a;n<b;n++){var r=new CLevelBut(q[d]+k.width/4,e+k.height/2,n+1,k,n+1>s_iLastLevel?!1:!0,c);r.addEventListenerWithParams(ON_MOUSE_UP,this._onButLevelRelease,this,n);l.push(r);d++;if(d===q.length&&(d=0,e+=k.height+20,f++,f>NUM_ROWS_PAGE_LEVEL)){g=!0;break}}c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.regX=c.getBounds().width/2;c.regY=c.getBounds().height/2;g&&this._createNewLevelPage(n+
1,b)};this._onRight=function(){m[c].visible=!1;c++;c>=m.length&&(c=0);m[c].visible=!0};this._onLeft=function(){m[c].visible=!1;c--;0>c&&(c=m.length-1);m[c].visible=!0};this._onButLevelRelease=function(a){s_oMain.levelSelected(a+1)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,b,e,d,f,g){var c,k,l,q=[],m=[],u,r,n,t,v;this._init=function(a,b,d,e,f){k=[];l=[];t=new createjs.Container;v.addChild(t);var g=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});c=f;n=createSprite(g,"state_"+c,e.width/2/2,e.height/2,e.width/2,e.height);n.mouseEnabled=f;n.x=a;n.y=b;n.stop();s_bMobile||(n.cursor="pointer");t.addChild(n);q.push(n);u=new createjs.Text(d,"bold 60px "+
FONT_GAME,"#004e6f");u.x=a;u.y=b+20;u.textAlign="center";u.textBaseline="alphabetic";u.lineWidth=200;u.outline=6;t.addChild(u);r=new createjs.Text(d,"bold 60px "+FONT_GAME,"#fff");r.x=a;r.y=b+20;r.textAlign="center";r.textBaseline="alphabetic";r.lineWidth=200;t.addChild(r);f||(r.color="#b4b4b4",u.color="#606161");this._initListener()};this.unload=function(){t.off("mousedown",this.buttonDown);t.off("pressup",this.buttonRelease);t.removeChild(n)};this._initListener=function(){t.on("mousedown",this.buttonDown);
t.on("pressup",this.buttonRelease)};this.viewBut=function(a){t.addChild(a)};this.addEventListener=function(a,b,c){k[a]=b;l[a]=c};this.addEventListenerWithParams=function(a,b,c,d){k[a]=b;l[a]=c;m=d};this.ifClickable=function(){return!0===t.mouseEnabled?1:0};this.setActive=function(a,b){c=b;q[a].gotoAndStop("state_"+c);q[a].mouseEnabled=!0;c?(r.color="#69b8d5",u.color="#004e6f"):(r.color="#b4b4b4",u.color="#606161")};this.buttonRelease=function(){c&&(playSound("click",1,0),k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(l[ON_MOUSE_UP],
m))};this.buttonDown=function(){k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],m)};this.setPosition=function(a,b){t.x=a;t.y=b};this.setVisible=function(a){t.visible=a};v=g;this._init(a,b,e,d,f,g)}
function CMsgBox(a,b,e,d){var f,g,c,k,l,q,m;this._init=function(a,b,d,e){f=[];g=[];m=new createjs.Container;s_oStage.addChild(m);var v=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));m.addChild(v);c=new createjs.Text("","24px "+FONT_GAME,"#fff");c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=220;c.x=CANVAS_WIDTH/2+20;c.y=250;m.addChild(c);k=new CTextButton(CANVAS_WIDTH/2-100,CANVAS_HEIGHT-150,s_oSpriteLibrary.getSprite("but_generic_small"),"LEFT",FONT_GAME,"#ffffff",30,m);k.addEventListener(ON_MOUSE_UP,
this._onButLeftDownRelease,this);l=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-150,s_oSpriteLibrary.getSprite("but_generic_small"),"CENTER",FONT_GAME,"#ffffff",30,m);l.addEventListener(ON_MOUSE_UP,this._onButCenterDownRelease,this);q=new CTextButton(CANVAS_WIDTH/2+90,CANVAS_HEIGHT-150,s_oSpriteLibrary.getSprite("but_generic_small"),"LEFT",FONT_GAME,"#ffffff",30,m);q.addEventListener(ON_MOUSE_UP,this._onButRightDownRelease,this);this.show(a,b,d,e)};this.show=function(a,b,d,e){c.text=a;""!==b?(k.changeText(b),
k.setVisible(!0)):k.setVisible(!1);""!==d?(l.changeText(d),l.setVisible(!0)):l.setVisible(!1);""!==e?(q.changeText(e),q.setVisible(!0)):q.setVisible(!1)};this.hide=function(){this.unload();s_oStage.removeChild(m)};this.unload=function(){k.unload();l.unload();q.unload()};this.addEventListener=function(a,b,c){f[a]=b;g[a]=c};this._onButLeftDownRelease=function(){f[ON_MSG_BOX_LEFT_BUT]&&(f[ON_MSG_BOX_LEFT_BUT].call(g[ON_MSG_BOX_LEFT_BUT]),m.visible=!1)};this._onButCenterDownRelease=function(){f[ON_MSG_BOX_CENTER_BUT]&&
(f[ON_MSG_BOX_CENTER_BUT].call(g[ON_MSG_BOX_CENTER_BUT]),m.visible=!1)};this._onButRightDownRelease=function(){f[ON_MSG_BOX_RIGHT_BUT]&&(f[ON_MSG_BOX_RIGHT_BUT].call(g[ON_MSG_BOX_RIGHT_BUT]),m.visible=!1)};this._init(a,b,e,d)};
